#!/bin/bash
# automount - Connecting to a NAS local and remote

# This script mounts a directory via sshfs. 
# A user can configure two mount options - a remote and a local one
# This is usefull if connecting to a Network Attached Storage (NAS) from the Internet involves a relay which is not needed if the user is in the same network as the NAS.

# A Config file has to look like this and named automount.conf
# DIRNAME=folder
# HOST_LOCAL=192.168.10.2
# PORT_LOCAL=22
# HOST_REMOTE=relay.remote.net
# PORT_REMOTE=22
# PATH_SERVER="/mnt/folder"
# MNT_PNT="/mnt/folder"

# Search for config files
if [ -f "$HOME/.config/automount/automount.conf" ] ; then
	source "$HOME/.config/automount/automount.conf" 
elif [ -f "$HOME/.config/automount.conf" ] ; then
	source "$HOME/.config/automount.conf" 
elif [ -f "$HOME/.automount.conf" ] ; then
	source "$HOME/.automount.conf" 
else 
	echo "No config file found. Create one first"
	exit 1
fi

# Test if folder is mounted
test_mountpoint () {
	findmnt $MNT_PNT &> /dev/null
}

# Mount locally
mount_local () {
	sshfs $USERNAME@$HOST_LOCAL:$PATH_SERVER $MNT_PNT -o ServerAliveInterval=1,ServerAliveCountMax=15 -p $PORT_LOCAL &> /dev/null
}

# Mount remote
mount_remote () {
	sshfs $USERNAME@$HOST_REMOTE:$PATH_SERVER $MNT_PNT -o ServerAliveInterval=1,ServerAliveCountMax=15 -p $PORT_REMOTE &> /dev/null
}

case $1 in 
	"remote")
		if mount_remote && test_mountpoint ; then
				echo "Mounted $DIRNAME remotely"
				exit 0
		else 
				echo "Could not mounted $DIRNAME remotely"
				exit 1
		fi
		;;
	"local")
		if mount_local && test_mountpoint ; then
				echo "Mounted $DIRNAME locally"
				exit 0
		else 
				echo "Could not mounted $DIRNAME locally"
				exit 1
		fi
		;;
	"umount")
		umount $MNT_PNT
		exit 0
		;;
	"show-config")
		echo "USERNAME=$USERNAME"
		echo "DIRNAME=$DIRNAME"
		echo "HOST_LOCAL=$HOST_LOCAL"
		echo "PORT_LOCAL=$PORT_LOCAL"
		echo "HOST_REMOTE=$HOST_REMOTE"
		echo "PORT_REMOTE=$PORT_REMOTE"
		echo "PATH_SERVER=$PATH_SERVER"
		echo "MNT_PNT=$MNT_PNT"
		exit 0
		;;
	*)
		echo "No option given"
		exit 1
		;;
esac

