#!/usr/bin/env bash
# Compress a PDF using Ghostscript
# $1 input file name
# $2 output file name
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/prepress -dNOPAUSE -dQUIET -dBATCH -sOutputFile=$2 $1
